---
- name: catwalk | extract nim
  get_url:
    url: "https://nim-lang.org/download/nim-{{ nim_version }}-linux_x64.tar.xz"
    dest: "{{ home }}"
    mode: 0755

- name: catwalk | create folder for nim
  file:
    path: "{{ home }}/nim-{{ nim_version }}"
    state: directory
    mode: 0755

- name: catwalk | extract nim
  unarchive:
    src: "{{ home }}/nim-{{ nim_version }}-linux_x64.tar.xz"
    dest: "{{ home }}/nim-{{ nim_version }}"
    remote_src: no

- name: catwalk | remove nim archive file
  file:
    path: "{{ home }}/nim-{{ nim_version }}-linux_x64.tar.xz"
    state: absent

- name: catwalk | append nim to PATH
  shell: "export PATH={{ home }}/nim-{{ nim_version }}/bin:$PATH"

- name: catwalk | add PATH to bashrc
  lineinfile:
    dest: "~/.bashrc"
    line: export PATH="$HOME/nim-{{ nim_version }}/bin:$PATH"

- name: catwalk | echo PATH
  shell: "echo $PATH"

- name: catwalk | check if nim is running
  shell: "echo $PATH"
  environment:
    PATH: "{{ home }}/nim-{{ nim_version }}/bin:$PATH"

- name: catwalk | check if nim is running
  shell: "nim -v"
  environment:
    PATH: "{{ home }}/nim-{{ nim_version }}/bin:$PATH"