---
- name: catwalk | extract nim
  get_url:
    url: "https://nim-lang.org/download/nim-{{ nim_version }}-linux_x64.tar.xz"
    dest: "{{ home }}"
    mode: 0755

- name: catwalk | extract nim
  unarchive:
    src: "{{ home }}/nim-{{ nim_version }}-linux_x64.tar.xz"
    dest: "{{ home }}"
    remote_src: no

- name: catwalk | remove nim archive file
  file:
    path: "{{ home }}/nim-{{ nim_version }}-linux_x64.tar.xz"
    state: absent

- name: catwalk | add PATH to bashrc
  lineinfile:
    dest: "~/.bashrc"
    line: export PATH="{{ home }}/nim-{{ nim_version }}/bin:$PATH"

- name: catwalk | check folder
  shell: "ls {{ home }}/nim-{{ nim_version }}"

- name: catwalk | check if nim is running
  shell: "{{ home }}/nim-{{ nim_version }}/bin/nim -v"

- name: catwalk | check if nim is running
  shell: "nim -v"
  environment:
    PATH: "{{ home }}/nim-{{ nim_version }}/bin:$PATH"

