---
- name: findn4 | clone the findNeighbours4 repository
  git:
    repo: https://github.com/davidhwyllie/findNeighbour4.git
    version: master
    dest: "{{ home }}/findNeighbours4"

- name: findn4 | delete version.py file
  file:
    path: "{{ home }}/findNeighbours4/version.py"
    state: absent

- name: findn4 | get version variable with setup.py
  shell: "python3 {{ home }}/findNeighbours4/setup.py --version"
  register: version_var

- name: findn4 | create version.py file
  copy:
    dest: "{{ home }}/findNeighbours4/version.py"
    content: "version = {{ version_var.stdout }}"

- name: findn4 | install virtual env findNeighbours4
  command:
    chdir: "{{ home }}/findNeighbours4"
    cmd: "pipenv install -e . --skip-lock"
  become: true

- name: findn4 | downgrade some dependencies to make it work
  command:
    chdir: "{{ home }}/findNeighbours4"
    cmd: "pipenv run pip install bokeh==2.4.0 pandas==1.5.3 sqlalchemy==1.4.48"
  become: true

- name: findn4 | add catwalk path to .env file for findn4
  copy:
    dest: "{{ home }}/findNeighbours4/.env"
    content: "CW_BINARY_FILEPATH={{ home }}/catwalk/cw_server"