### assumes ubuntu image
---
- name: update apt cache
  apt: update_cache=yes
  become: true

- name: install packages
  apt: 
      pkg: 
          - curl
          - build-essential
          - git
          - pkg-config
          - default-jre
          - unzip
      state: latest
  become: true

- name: configure python
  include_tasks: python.yml

- name: install mongodb
  include_tasks: mongodb.yml

- name: install catwalk
  include_tasks: catwalk.yml

# - name: test catwalk
#   include_tasks: test_catwalk.yml

- name: install findNeighbours4
  include_tasks: findn4.yml

# - name: test findNeighbours4
#   include_tasks: test_findn4.yml

- name: setup AC587 demo files
  include_tasks: findn4_demo_AC587.yml